-- 2026-09-14 입학 가상계좌 연결. 서비스/worker 중지 및 백업 후 적용. 운영 실행하지 않음.
SET @ddl = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='tuition_bills' AND COLUMN_NAME='admission_candidate_id')=0, 'ALTER TABLE tuition_bills ADD COLUMN admission_candidate_id BIGINT NULL', 'SELECT 1');
PREPARE admission_stmt FROM @ddl;
EXECUTE admission_stmt;
DEALLOCATE PREPARE admission_stmt;
SET @ddl = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='tuition_bills' AND COLUMN_NAME='admission_customer_name')=0, 'ALTER TABLE tuition_bills ADD COLUMN admission_customer_name VARCHAR(50) NULL', 'SELECT 1');
PREPARE admission_stmt FROM @ddl;
EXECUTE admission_stmt;
DEALLOCATE PREPARE admission_stmt;
SET @ddl = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='tuition_bills' AND COLUMN_NAME='admission_bank_code')=0, 'ALTER TABLE tuition_bills ADD COLUMN admission_bank_code VARCHAR(20) NULL', 'SELECT 1');
PREPARE admission_stmt FROM @ddl;
EXECUTE admission_stmt;
DEALLOCATE PREPARE admission_stmt;
SET @ddl = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='tuition_bills' AND COLUMN_NAME='admission_next_sync_at')=0, 'ALTER TABLE tuition_bills ADD COLUMN admission_next_sync_at DATETIME NULL', 'SELECT 1');
PREPARE admission_stmt FROM @ddl;
EXECUTE admission_stmt;
DEALLOCATE PREPARE admission_stmt;
SET @ddl = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='tuition_bills' AND COLUMN_NAME='admission_sync_complete')=0, 'ALTER TABLE tuition_bills ADD COLUMN admission_sync_complete BOOLEAN NOT NULL DEFAULT FALSE', 'SELECT 1');
PREPARE admission_stmt FROM @ddl;
EXECUTE admission_stmt;
DEALLOCATE PREPARE admission_stmt;
SET @ddl = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='tuition_bills' AND COLUMN_NAME='admission_sync_error')=0, 'ALTER TABLE tuition_bills ADD COLUMN admission_sync_error VARCHAR(100) NULL', 'SELECT 1');
PREPARE admission_stmt FROM @ddl;
EXECUTE admission_stmt;
DEALLOCATE PREPARE admission_stmt;
SET @ddl = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='payments' AND COLUMN_NAME='admission_candidate_id')=0, 'ALTER TABLE payments ADD COLUMN admission_candidate_id BIGINT NULL', 'SELECT 1');
PREPARE admission_stmt FROM @ddl;
EXECUTE admission_stmt;
DEALLOCATE PREPARE admission_stmt;
ALTER TABLE tuition_bills MODIFY student_id BIGINT NULL;
ALTER TABLE payments MODIFY student_id BIGINT NULL;
SET @ddl=IF((SELECT COUNT(*) FROM information_schema.TABLE_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=DATABASE() AND TABLE_NAME='tuition_bills' AND CONSTRAINT_NAME='uk_tuition_admission_candidate')=0,'ALTER TABLE tuition_bills ADD CONSTRAINT uk_tuition_admission_candidate UNIQUE(admission_candidate_id)','SELECT 1');
PREPARE admission_stmt FROM @ddl; EXECUTE admission_stmt; DEALLOCATE PREPARE admission_stmt;
SET @ddl=IF((SELECT COUNT(*) FROM information_schema.TABLE_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=DATABASE() AND TABLE_NAME='tuition_bills' AND CONSTRAINT_NAME='ck_tuition_owner')=0,'ALTER TABLE tuition_bills ADD CONSTRAINT ck_tuition_owner CHECK(student_id IS NOT NULL OR admission_candidate_id IS NOT NULL)','SELECT 1');
PREPARE admission_stmt FROM @ddl; EXECUTE admission_stmt; DEALLOCATE PREPARE admission_stmt;
SET @ddl=IF((SELECT COUNT(*) FROM information_schema.TABLE_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=DATABASE() AND TABLE_NAME='payments' AND CONSTRAINT_NAME='ck_payment_owner')=0,'ALTER TABLE payments ADD CONSTRAINT ck_payment_owner CHECK(student_id IS NOT NULL OR admission_candidate_id IS NOT NULL)','SELECT 1');
PREPARE admission_stmt FROM @ddl; EXECUTE admission_stmt; DEALLOCATE PREPARE admission_stmt;
