package com.msa4lmsv2payment.global.audit;

/**
 * 감사 로그에 기록되는 업무 액션 종류.
 */
public enum AuditAction {
    TUITION_BILL_CREATED,
    REFUND_REQUESTED,
    VIRTUAL_ACCOUNT_ISSUED,
    PAYMENT_APPROVED,
    PAYMENT_FAILED,
    REFUND_RETRIED,
    DOCUMENT_REVOKED,
    INSTALLMENT_PLAN_REQUESTED,
    INSTALLMENT_PLAN_REVIEWED,
    SCHOLARSHIP_APPLICATION_REQUESTED,
    SCHOLARSHIP_APPLICATION_REVIEWED,
    VIRTUAL_ACCOUNT_DEPOSIT_RECEIVED
}
